name: AdvancedEggHunt
version: 3.0.4
main: de.theredend2000.advancedegghunt.Main
api-version: 1.13
softdepend: [PlaceholderAPI]
website: https://www.spigotmc.org/resources/advancedegghunt.109085/
authors: [ TheRedEnd2000, GrafterCrafter ]

commands:
  AdvancedEggHunt:
    aliases:
      - aeh
      - advancedhunt
      - egghunt
      - eggs
      - easter

permissions:
  AdvancedEggHunt.command.reset:
    description: "Resets all plugin data"
  AdvancedEggHunt.command.settings:
    description: "Shows and allows for updating of config settings"
  AdvancedEggHunt.command.reload:
    description: "Reload plugin"
  AdvancedEggHunt.command.commands:
    description: "Reward commands that are ran when a player finds an egg"
  AdvancedEggHunt.command.placeEggs:
    description: "Allow a player to enter and exit egg placing mode"
  AdvancedEggHunt.command.eggImport:
    description: "Import a player head that is help in the main hand"
  AdvancedEggHunt.command.show:
    description: "Show the location of nearby placed eggs using glowing armor stands"
  AdvancedEggHunt.command.list:
    description: "List all placed eggs for the selected collection"

  AdvancedEggHunt.command.help:
    description: "Show a list of possible commands with short descriptions"
  AdvancedEggHunt.command.collection:
    description: "Change selected collection"
  AdvancedEggHunt.command.progress:
    description: "Shows the progress for eggs found"
  AdvancedEggHunt.command.leaderboard:
    description: "Shows the leaderboard for the egg hunt"
  AdvancedEggHunt.command.hint:
    description: "Shows a hint in the form of coordinates of a nearby egg that the player has not found yet"


  AdvancedEggHunt.BreakEgg:
    description: ""
  AdvancedEggHunt.PlaceEgg:
    description: ""
  AdvancedEggHunt.IgnoreCooldown:
    description: ""
  AdvancedEggHunt.ChangeCollections:
    description: ""
  AdvancedEggHunt.CreateCollection:
    description: ""
  AdvancedEggHunt.OpenRewards:
    description: ""
  AdvancedEggHunt.FindEggs:
    description: ""

  AdvancedEggHunt.group.admin:
    description: "Contains all essential admin permissions"
    default: op
    children:
      AdvancedEggHunt.command.reload: true
      AdvancedEggHunt.command.reset: true
      AdvancedEggHunt.command.settings: true
      AdvancedEggHunt.command.commands: true
      AdvancedEggHunt.command.placeEggs: true
      AdvancedEggHunt.command.show: true
      AdvancedEggHunt.command.list: true
      AdvancedEggHunt.command.eggImport: true

      AdvancedEggHunt.BreakEgg: true
      AdvancedEggHunt.PlaceEgg: true
      AdvancedEggHunt.ChangeCollections: true
      AdvancedEggHunt.CreateCollection: true
      AdvancedEggHunt.OpenRewards: true

      AdvancedEggHunt.group.default: true

  AdvancedEggHunt.group.default:
    description: "Contains all essential default permissions"
    default: true
    children:
      AdvancedEggHunt.command.help: true
      AdvancedEggHunt.command.collection: true
      AdvancedEggHunt.command.progress: true
      AdvancedEggHunt.command.leaderboard: true
      AdvancedEggHunt.command.hint: true
      AdvancedEggHunt.FindEggs: true