name: AdvancedHunt
version: 3.1.0
main: de.theredend2000.advancedhunt.Main
api-version: 1.13
softdepend: [PlaceholderAPI, NBTAPI, ProtocolLib]
website: https://www.spigotmc.org/resources/advancedegghunt.109085/
authors: [ TheRedEnd2000, GrafterCrafter ]

permissions:
  AdvancedHunt.command.reset:
    description: "Resets all plugin data"
  AdvancedHunt.command.settings:
    description: "Shows and allows for updating of config settings"
  AdvancedHunt.command.reload:
    description: "Reload plugin"
  AdvancedHunt.command.commands:
    description: "Reward commands that are ran when a player finds an egg"
  AdvancedHunt.command.place:
    description: "Allow a player to enter and exit egg placing mode"
  AdvancedHunt.command.eggImport:
    description: "Import a player head that is help in the main hand"
  AdvancedHunt.command.show:
    description: "Show the location of nearby placed eggs using glowing armor stands"
  AdvancedHunt.command.list:
    description: "List all placed eggs for the selected collection"

  AdvancedHunt.command.help:
    description: "Show a list of possible commands with short descriptions"
  AdvancedHunt.command.collection:
    description: "Change selected collection"
  AdvancedHunt.command.progress:
    description: "Shows the progress for eggs found"
  AdvancedHunt.command.leaderboard:
    description: "Shows the leaderboard for the egg hunt"
  AdvancedHunt.command.hint:
    description: "Shows a hint in the form of coordinates of a nearby egg that the player has not found yet"


  AdvancedHunt.BreakEgg:
    description: ""
  AdvancedHunt.PlaceEgg:
    description: ""
  AdvancedHunt.IgnoreCooldown:
    description: ""
  AdvancedHunt.ChangeCollections:
    description: ""
  AdvancedHunt.CreateCollection:
    description: ""
  AdvancedHunt.OpenRewards:
    description: ""
  AdvancedHunt.FindEggs:
    description: ""

  AdvancedHunt.group.admin:
    description: "Contains all essential admin permissions"
    default: op
    children:
      AdvancedHunt.command.reload: true
      AdvancedHunt.command.reset: true
      AdvancedHunt.command.settings: true
      AdvancedHunt.command.commands: true
      AdvancedHunt.command.place: true
      AdvancedHunt.command.show: true
      AdvancedHunt.command.list: true
      AdvancedHunt.command.eggImport: true

      AdvancedHunt.BreakEgg: true
      AdvancedHunt.PlaceEgg: true
      AdvancedHunt.ChangeCollections: true
      AdvancedHunt.CreateCollection: true
      AdvancedHunt.OpenRewards: true

      AdvancedHunt.group.default: true

  AdvancedHunt.group.default:
    description: "Contains all essential default permissions"
    default: true
    children:
      AdvancedHunt.command.help: true
      AdvancedHunt.command.collection: true
      AdvancedHunt.command.progress: true
      AdvancedHunt.command.leaderboard: true
      AdvancedHunt.command.hint: true
      AdvancedHunt.FindEggs: true